[package]
name = "transfer-lib"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
curl = "0.4"
thiserror = "1"
xshell = "0.2"
