[package]
name = "transfer-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
reqwest = { version = "0.11", features = ["stream"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
xshell = "0.2"
