[package]
name = "transfer-config"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
toml = "0.7"
