copy = [
    { from = "config/dotfiles/git/.gitconfig", to = "~/" },
    { from = "config/dotfiles/rg/ripgreprc", to = "~/.config/ripgrep/" },
    { from = "config/dotfiles/bat/config", to = "~/.config/bat/" },
    { from = "config/dotfiles/fnm/fnm.fish", to = "~/.config/fish/conf.d/" },
    { from = "config/dotfiles/vim/", to = "~/.config/nvim/" },
    { from = "config/dotfiles/fish/", to = "~/.config/fish/functions/" },
    { from = "/System/Applications/Utilities/Terminal.app/Contents/Resources/Fonts/", to = "~/Library/Fonts/" },
]

download = [
    { from = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", to = "~/.local/share/nvim/site/autoload/plug.vim" },
    { from = "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish", run = true },
]

run = [
    { script_path = "config/scripts/macos.sh", command = "bash", title = "Configuring macOS" },
    { script_path = "config/scripts/setup.fish", command = "fish", title = "Installing fish packages" },
]

reminders = [
    { instruction = "Set fish as default shell", command = "chsh -s /opt/homebrew/bin/fish" },
    { instruction = "Enable fish vi keybindings", command = "fish_vi_key_bindings" },
    { instruction = "Load rbenv", command = "rbenv init" },
]
