[package]
name = "transfer"
authors.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
